on: push
name: Update Website

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: my-portfolio
      - uses: actions/checkout@v4
        with:
          repository: hobart2967/hobart2967.github.io
          path: github-pages-repo
      - run: |
          cd github-pages-repo
          rm -rf *
      - run: |
          git config --unset-all http.https://github.com/.extraheader
          git config --global user.name 'hobart2967-bot'
          git config --global user.email 'hobart2967@users.noreply.github.com'
          cp -r my-portfolio/website/dist/website/* github-pages-repo
          cd github-pages-repo
          git commit -am "Update from my-portfolio"
          git push

